config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  resources :personals
  resources :coins
  
  #para fazer rotas manuais
  #get '/moedas', to: 'coins#index'

  root to: 'welcome#index'

  delete 'coins/:id(.:format)', :to => 'coins#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
	belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
	has_many :coins #optional :true
end

app/models/personal.rb
class Personal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_locale

	def set_locale
		if params[:locale]
			cookies[:locale] = params[:locale]
		end

		if cookies[:locale]
			if I18n.locale != cookies[:locale]
				I18n.locale = cookies[:locale]
			end
		end
	end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only: [:new, :edit, :update, :create]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: [:show, :edit, :update, :destroy]

  # GET /personals
  # GET /personals.json
  def index
    @personals = Personal.all
  end

  # GET /personals/1
  # GET /personals/1.json
  def show
  end

  # GET /personals/new
  def new
    @personal = Personal.new
  end

  # GET /personals/1/edit
  def edit
  end

  # POST /personals
  # POST /personals.json
  def create
    @personal = Personal.new(personal_params)

    respond_to do |format|
      if @personal.save
        format.html { redirect_to @personal, notice: 'Personal was successfully created.' }
        format.json { render :show, status: :created, location: @personal }
      else
        format.html { render :new }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personals/1
  # PATCH/PUT /personals/1.json
  def update
    respond_to do |format|
      if @personal.update(personal_params)
        format.html { redirect_to @personal, notice: 'Personal was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal }
      else
        format.html { render :edit }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1
  # DELETE /personals/1.json
  def destroy
    @personal.destroy
    respond_to do |format|
      format.html { redirect_to personals_url, notice: 'Personal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal
      @personal = Personal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_params
      params.require(:personal).permit(:description, :age, :sex)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  	cookies[:curso] = "Curso de Ruby on Rails"
  	@nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


	def app_title
		"Cripto Wallet - Ruby"
	end

	def env_rails
		if Rails.env.development?
			"development"
		elsif Rails.env.production?
			"production"
		else
			"test"
		end
	end

	def site_name
		"Cripto Wallet - Ruby"
	end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>:
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :acronym %>:
    <%= form.text_field :acronym , class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :mining_type %>:

    <%= form.select('mining_type_id', @mining_type_options,{include_blank: t('links.select')},{class: 'form-control'}) %>
  </div>

  <div class="field">
    <%= form.label :url_image %>:
    <%= form.text_field :url_image , class: 'form-control'%>
  </div>
  <br>
  <div class="actions">
    <%= form.submit t('links.send') , class: 'btn btn-success' %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<div class="col-md-6 offset-md-3">
	<h1><%=t('links.edit')%></h1>

	<%= render 'form', coin: @coin %>
<br>
	<%= link_to t('links.show'), @coin, class: 'btn btn-primary' %> 
	<%= link_to t('links.delete'), @coin, method: :delete, data: { confirm: t('links.confirm') }, class: 'btn btn-danger' %>
	<%= link_to t('links.back'), coins_path, class: 'btn btn-primary' %>
</div>

app/views/coins/index.html.erb
<div class="col-md-12">
  <p id="notice"><%= notice %></p>

  <h1><%=@coins.model_name.human(count: @coins)%></h1>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%=@coins.human_attribute_name(:description)%></th>
          <th><%=@coins.human_attribute_name(:acronym)%></th></th>
          <th><%=@coins.human_attribute_name(:mining_type)%><th><%=@coins.human_attribute_name(:url_image)%>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @coins.each do |coin| %>
          <tr ondblclick="location.href = '<%= coin_path(coin.id) %>'">
            <td><%= coin.description %></td>
            <td><%= coin.acronym %></td>
            <td><%= coin.mining_type.acronym %></td>
            <td><%= image_tag coin.url_image, size:'25x25' %></td>
            <td><%= link_to t('links.show'), coin %></td>
            <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
            <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: t('links.confirm') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to t('links.new'), new_coin_path, class: 'btn btn-primary' %>
</div>

app/views/coins/new.html.erb
<div class="col-md-6 offset-md-3">
	<h1><%= t('links.new')%></h1>

	<%= render 'form', coin: @coin %>

	<%= link_to t('links.back'), coins_path %>
</div>

app/views/coins/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong><%=Coin.human_attribute_name(:description)%>:</strong>
	  <%= @coin.description %>
	</p>

	<p>
	  <strong><%=Coin.human_attribute_name(:acronym)%>:</strong>
	  <%= @coin.acronym %>
	</p>

	<p>
	  <strong><%=Coin.human_attribute_name(:mining_type)%>:</strong>
	  <%= @coin.mining_type.acronym %> - <%= @coin.mining_type.description %>
	</p>

	  <strong><%=Coin.human_attribute_name(:url_image)%>:</strong>
	<p>
	  <%= image_tag @coin.url_image, size: '50x50', class: 'image-responsive' %>
	</p>
	<%= link_to t('links.edit'), edit_coin_path(@coin), class: 'btn btn-warning' %> 
	<%= link_to t('links.delete'), @coin, method: :delete, data: { confirm: t('links.confirm') }, class: 'btn btn-danger' %>
	<%= link_to t('links.back'), coins_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">
    <%= link_to image_tag("logo.png", width: 100), root_path %>
  </a>
  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('text-site.menu.home'), root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('text-site.menu.coin'), coins_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('text-site.menu.mining-type'), mining_types_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'English', url_for(:locale => 'en'), class: 'nav-link'%>
      </li>

      <li class="nav-item">
        <%=link_to 'Português Brasileiro', url_for(:locale => 'pt-BR'), class: 'nav-link'%>
      </li>
    </ul>
  </div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : app_title %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    params[:controller], :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>

   
        <%= yield(:head) %>
  </head>

  <body>
    
    <%= render 'layouts/menu' %>
    <div class="container-fluid">
      <%= yield %>
    </div> <!--! end of .container -->
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>:
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :acronym %>:
    <%= form.text_field :acronym, class: 'form-control' %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit t('links.send'), class: 'btn btn-success' %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<div class="col-md-6 offset-md-3">
	<h1><%= t('links.edit')%></h1>

	<%= render 'form', mining_type: @mining_type %>
<br>
	<%= link_to t('links.show'), @mining_type, class: 'btn btn-primary' %> 
	<%= link_to t('links.delete'), @mining_type, method: :delete, data: { confirm: t('links.confirm') }, class: 'btn btn-danger' %>
	<%= link_to t('links.back'), mining_types_path, class: 'btn btn-primary' %>

</div>

app/views/mining_types/index.html.erb
<div class="col-md-12">
  <p id="notice"><%= notice %></p>

   <h1><%=@mining_types.model_name.human(count: @mining_types)%></h1>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%=@mining_types.human_attribute_name(:description)%></th>
           <th><%=@mining_types.human_attribute_name(:acronym)%></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @mining_types.each do |mining_type| %>
          <tr>
            <td><%= mining_type.description %></td>
            <td><%= mining_type.acronym %></td>
            <td><%= link_to t('links.show'), mining_type %></td>
            <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
            <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('links.confirm') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to t('links.new'), new_mining_type_path, class: "btn btn-primary" %>

</div>

app/views/mining_types/new.html.erb
<div class="col-md-6 offset-md-3">
	<h1><%=t('links.new')%></h1>

	<%= render 'form', mining_type: @mining_type %>

	<%= link_to t('links.back'), mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= MiningType.human_attribute_name(:description)%>: </strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong><%= MiningType.human_attribute_name(:acronym)%>: </strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class: 'btn btn-warning' %>
<%= link_to t('links.delete'), @mining_type, method: :delete, data: { confirm: t('links.confirm') }, class: 'btn btn-danger' %>

<%= link_to t('links.back'), mining_types_path, class: 'btn btn-primary' %>

app/views/personals/_form.html.erb
<%= form_with(model: personal, local: true) do |form| %>
  <% if personal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personal.errors.count, "error") %> prohibited this personal from being saved:</h2>

      <ul>
      <% personal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personals/edit.html.erb
<h1>Editing Personal</h1>

<%= render 'form', personal: @personal %>

<%= link_to 'Show', @personal %> |
<%= link_to 'Back', personals_path %>

app/views/personals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personals</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Age</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personals.each do |personal| %>
      <tr>
        <td><%= personal.description %></td>
        <td><%= personal.age %></td>
        <td><%= personal.sex %></td>
        <td><%= link_to 'Show', personal %></td>
        <td><%= link_to 'Edit', edit_personal_path(personal) %></td>
        <td><%= link_to 'Destroy', personal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal', new_personal_path %>

app/views/personals/new.html.erb
<h1>New Personal</h1>

<%= render 'form', personal: @personal %>

<%= link_to 'Back', personals_path %>

app/views/personals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @personal.description %>
</p>

<p>
  <strong>Age:</strong>
  <%= @personal.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @personal.sex %>
</p>

<%= link_to 'Edit', edit_personal_path(@personal) %> |
<%= link_to 'Back', personals_path %>

app/views/welcome/_menu.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><%= site_name %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Moedas", coins_path %></li>
        <li><%= link_to "Tipos de Mineração", mining_types_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<div class="col-md-12">

	<div class="jumbotron">
	  <h1 class="display-4"><%=t("text-site.home.welcome")%></h1>
	  <hr class="my-4">
	  	<p><%=t("text-site.home.date")%>: <%= l(Date.today) %></p>

		<p><%=t("text-site.home.env")%>:  <strong><%= env_rails %>
			<br>
		<%= link_to Coin.model_name.human, coins_path, class: 'btn btn-primary'%>
		<%= link_to MiningType.model_name.human, mining_types_path, class: 'btn btn-primary'%>
	</div>
	
</div>